version: "3.8"

networks:
    ecommerce_app:

volumes:
    db:
    pma:

services:
    app:
        build:
            context: ./
            dockerfile: ./docker/php/Dockerfile
        image: ecommerce-app
        container_name: ecommerce-app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        ports:
            - "9001:9000"
        depends_on:
            - mariadb
        networks:
            - ecommerce_app

    mariadb:
        image: mariadb:10.5.9
        container_name: ecommerce-db
        restart: unless-stopped
        tty: true
        ports:
            - "4307:3306"
        volumes:
            - db:/var/lib/mysql

        environment:
            MYSQL_DATABASE: ecommerce_db
            MYSQL_USER: user
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
        networks:
            - ecommerce_app

    nginx:
        image: nginx:1.23.3-alpine
        container_name: nginx1
        ports:
            - "8001:80"
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
            - mariadb
        networks:
            - ecommerce_app

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin1
        environment:
            PMA_PMADB: 1
            PMA_ARBITRARY: 1
            PMA_HOST: mariadb
            PMA_PORT: 3306
            PMA_USER: user
            PMA_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
        restart: always
        depends_on:
            - mariadb
        ports:
            - "81:80"
        volumes:
            - "pma:/etc/phpmyadmin/config.user.inc.php"
        networks:
            - ecommerce_app
        links:
            - mariadb

    nextjs:
        build:
            context: .
            dockerfile: ./docker/node/Dockerfile
        image: nextjs
        container_name: nextjs1
        ports:
            - "3001:3000"
        volumes:
            - ./public/front/:/app
        networks:
            - ecommerce_app
